name: Build & Publish

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  NODE_VERSION: 20

jobs:
  next-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          provenance: true
          push: true
          build-args: |
            NODE_VERSION=${{env.NODE_VERSION}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
