name: Build & Publish

on:
    push:
        branches:
            - "**"
            - "!dependabot/**"
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    NODE_VERSION: 20

jobs:
    next-build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # This action makes sure that we keep the exact same names and tags
            # as the source ones, we just prepend our own repository as a namespace
            # before it.
            #
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ github.repository }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern=v{{version}}
                      type=semver,pattern=v{{major}}.{{minor}}
                      type=semver,pattern=v{{major}}
                      type=sha

            # Build and push
            #
            # - amd64 and arm64 (think future proof)
            # - we keep the exact same name and tag
            # - publish as a package for this repository
            #
            - name: Build and push image
              uses: docker/build-push-action@v5
              with:
                  provenance: true
                  push: true
                  build-args: |
                      NODE_VERSION=${{env.NODE_VERSION}}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
